name: Sync Fork

on:
  schedule:
    - cron: '*/30 * * * *' # 每30分钟执行一次
  workflow_dispatch: # 允许通过按钮点击触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: tgymnich/fork-sync@v1.8
        with:
          owner: llvm
          base: master
          head: master
